# 13 20 4 2 14 22 5
root={
    'key':13,
    'left':{
        'key':4,
        'left':{
            'key':2,
            'left':{},
            'right':{}
            },
        'right':{
            'key':5,
            'left':{},
            'right':{}
        }
        },
    'right':{
        'key':20,
        'left':{
            'key':14,
            'left':{},
            'right':{}
            },
        'right':{
            'key':20,
            'left':{},
            'right':{}
        }
    }
}